version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "17:30"
      timezone: America/Vancouver
    open-pull-requests-limit: 10
    reviewers:
      - qjack001
    assignees:
      - qjack001

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "17:30"
      timezone: America/Vancouver
    open-pull-requests-limit: 10
    reviewers:
      - qjack001
    assignees:
      - qjack001